from __future__ import annotations

import re

from .models import ReconciledBook


def _clean(value: object) -> str:
    return " ".join(str(value or "").replace("\x00", "").split())


def _line(tag: str, value: object) -> str | None:
    cleaned = _clean(value)
    return f"{tag}  - {cleaned}" if cleaned else None


def page_total(book: ReconciledBook) -> str:
    if _clean(book.num_pages).isdigit():
        return _clean(book.num_pages)
    extent = _clean(book.extent)
    matches = re.findall(r"\b(\d{1,5})\s*(?:hlm\.?|halaman|p\.?|pages?|pg\.?)\b", extent, flags=re.I)
    return matches[-1] if matches else ""


def _audit_note(book: ReconciledBook) -> str:
    sources = "; ".join(
        f"{record.source}: {record.source_url}" for record in book.source_records if record.source_url
    )
    parts = [
        "Generated by ISBN-to-Zotero after independent-source reconciliation.",
        f"Assessment: {book.confidence}. {book.reason}",
    ]
    if book.extent:
        parts.append(f"Physical description reported by source: {book.extent}.")
    if book.conflicts:
        rendered = "; ".join(f"{field} = {' | '.join(values)}" for field, values in book.conflicts.items())
        parts.append(f"Source conflicts retained for review: {rendered}.")
    if sources:
        parts.append(f"Source records: {sources}")
    return " ".join(parts)


def book_to_ris(book: ReconciledBook) -> str:
    if not book.title:
        raise ValueError("RIS export requires a verified title")
    lines: list[str] = ["TY  - BOOK"]
    full_title = book.title
    if book.subtitle and book.subtitle.casefold() not in book.title.casefold():
        full_title = f"{book.title}: {book.subtitle}"
    values = [_line("TI", full_title)]
    lines.extend(value for value in values if value)
    lines.extend(value for person in book.authors if (value := _line("AU", person)))
    lines.extend(value for person in book.editors if (value := _line("ED", person)))
    lines.extend(value for person in book.translators if (value := _line("A4", person)))
    values = [
        _line("PY", book.date),
        _line("ET", book.edition),
        _line("CY", book.place),
        _line("PB", book.publisher),
        _line("SP", page_total(book)),
        _line("LA", "; ".join(book.languages)),
        _line("AB", book.abstract),
    ]
    lines.extend(value for value in values if value)
    lines.extend(value for isbn in book.isbns if (value := _line("SN", isbn)))
    lines.extend(value for subject in book.subjects if (value := _line("KW", subject)))
    if book.printing:
        lines.append(_line("N1", f"Printing statement: {book.printing}") or "")
    lines.extend(value for note in book.notes if (value := _line("N1", note)))
    lines.append(_line("N1", _audit_note(book)) or "")
    if book.source_records:
        lines.append(_line("UR", book.source_records[0].source_url) or "")
    lines.append("ER  -")
    return "\r\n".join(line for line in lines if line) + "\r\n"


def books_to_ris(books: list[ReconciledBook]) -> str:
    return "".join(book_to_ris(book) for book in books)


def safe_filename(book: ReconciledBook, suffix: str = ".ris") -> str:
    isbn = next((value for value in book.isbns if len(value) == 13), "") or next(iter(book.isbns), "book")
    title = re.sub(r"[^A-Za-z0-9]+", "-", book.title).strip("-")[:55]
    return f"{isbn}-{title or 'book'}{suffix}"
