import type { ReconciledBook } from "./types.ts";

function clean(value: unknown): string {
  return String(value ?? "").replaceAll("\0", "").trim().replace(/\s+/g, " ");
}

function line(tag: string, value: unknown): string | null {
  const cleaned = clean(value);
  return cleaned ? `${tag}  - ${cleaned}` : null;
}

export function pageTotal(book: ReconciledBook): string {
  if (/^\d+$/.test(clean(book.num_pages))) return clean(book.num_pages);
  const matches = [...clean(book.extent).matchAll(/\b(\d{1,5})\s*(?:hlm\.?|halaman|p\.?|pages?|pg\.?)\b/gi)];
  return matches.at(-1)?.[1] ?? "";
}

function auditNote(book: ReconciledBook): string {
  const sources = book.source_records
    .filter(record => record.source_url)
    .map(record => `${record.source}: ${record.source_url}`)
    .join("; ");
  const parts = [
    "Generated by ISBN-to-Zotero after independent-source reconciliation.",
    `Assessment: ${book.confidence}. ${book.reason}`,
  ];
  if (book.extent) parts.push(`Physical description reported by source: ${book.extent}.`);
  if (Object.keys(book.conflicts).length) {
    const rendered = Object.entries(book.conflicts).map(([field, values]) => `${field} = ${values.join(" | ")}`).join("; ");
    parts.push(`Source conflicts retained for review: ${rendered}.`);
  }
  if (sources) parts.push(`Source records: ${sources}`);
  return parts.join(" ");
}

export function bookToRIS(book: ReconciledBook): string {
  if (!book.title) throw new Error("RIS export requires a verified title");
  const lines = ["TY  - BOOK"];
  const fullTitle = book.subtitle && !book.title.toLocaleLowerCase().includes(book.subtitle.toLocaleLowerCase())
    ? `${book.title}: ${book.subtitle}`
    : book.title;
  lines.push(line("TI", fullTitle)!);
  for (const person of book.authors) lines.push(line("AU", person)!);
  for (const person of book.editors) lines.push(line("ED", person)!);
  for (const person of book.translators) lines.push(line("A4", person)!);
  for (const [tag, value] of [
    ["PY", book.date],
    ["ET", book.edition],
    ["CY", book.place],
    ["PB", book.publisher],
    ["SP", pageTotal(book)],
    ["LA", book.languages.join("; ")],
    ["AB", book.abstract],
  ]) {
    const rendered = line(tag, value);
    if (rendered) lines.push(rendered);
  }
  for (const isbn of book.isbns) lines.push(line("SN", isbn)!);
  for (const subject of book.subjects) lines.push(line("KW", subject)!);
  if (book.printing) lines.push(line("N1", `Printing statement: ${book.printing}`)!);
  for (const note of book.notes) lines.push(line("N1", note)!);
  lines.push(line("N1", auditNote(book))!);
  if (book.source_records.length) {
    const url = line("UR", book.source_records[0].source_url);
    if (url) lines.push(url);
  }
  lines.push("ER  -");
  return `${lines.filter(Boolean).join("\r\n")}\r\n`;
}

export function safeFilename(book: ReconciledBook, suffix = ".ris"): string {
  const isbn = book.isbns.find(value => value.length === 13) ?? book.isbns[0] ?? "book";
  const title = book.title.replace(/[^A-Za-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 55);
  return `${isbn}-${title || "book"}${suffix}`;
}
